### ISSUE TITLE
Incorrectly filtering External Requests when navigating from menu

### ISSUE THREAD

**Issue by monsieurBelbo** [nominal-systems/dmi-api-admin-ui#32]
1. Go to the External Requests page by clicking the menu item in the sidebar
2. Verify that the default filter (on the UI and on the URL) should be Response Status: 4xx, 5xx
3. 2xx requests are shown

![Image](https://github.com/user-attachments/assets/7967cb64-2dca-48e0-b2d2-f114ebd95872)

Filtering by response status should work accordingly.

This only seems to happen when accessing the page from the sidebar, not when directly loading it. In fact, the request done in this scenario is to `admin/external-requests?page=1&limit=20` (note that no status param is included)

**Comment by Ceibo** [comment]
I tested it and now it's working as expected.
