### ISSUE TITLE
Integrations list not displaying correctly.

### ISSUE THREAD

**Issue by Ceibo** [nominal-systems/dmi-api-admin-ui#39]
The separators between rows are missing, but most importantly, the Practice column is “collapsed” vertically, taking up more space than it should. Column ID may be taking too much space.
This applies to **Dashboard —> Integrations** and **Integrations**.

Using the browser and resolution.
DEVV2 (above) vs UAT (below).
![Screenshot_2024-09-30_at_2_07_45 AM](https://github.com/user-attachments/assets/9836e0b4-eed7-4641-8531-2eaaccab9394)
![Screenshot_2024-09-30_at_2_07_53 AM](https://github.com/user-attachments/assets/87b184f4-ec51-4848-a1f4-d74d8ea0c809)

**Comment by monsieurBelbo** [comment]
What resolution is that @Ceibo ?

**Comment by Ceibo** [comment]
Resolution was 1280px x 694px. It's a bit low, but is still used on several devices.
Now it's fixed, closing the issue.
