### ISSUE TITLE
Add links to filterer errors in External Requests error chart

### ISSUE THREAD

**Issue by monsieurBelbo** [nominal-systems/dmi-api-admin-ui#46]
Add a link to each section of the stacked column charts that goes to the filtered External Request list

**Comment by Ceibo** [comment]
When there's a provider with a large number of errors, it's not possible to click on another provider that has very few:
<img width="496" alt="Screenshot 2024-10-15 at 10 20 50 AM" src="https://github.com/user-attachments/assets/424a701f-78c0-4788-aae3-b37141c32548">

Not sure if this is fixable or expected, but other than that it's working fine and we can close the issue.

**Comment by monsieurBelbo** [comment]
Could eventually be worked-around by clicking on the legend (instead of the bars), but lets close this one for now.
