### ISSUE TITLE
Show species in breeds tab

### ISSUE THREAD

**Issue by monsieurBelbo** [nominal-systems/dmi-api-admin-ui#50]

**Comment by Ceibo** [comment]
When going to `Reference data` tab, it doesn't automatically show the list of "Breeds/Species/Sexes", the user needs to use the `Search` button.
<img width="1278" alt="Screenshot 2024-10-01 at 6 22 20 PM" src="https://github.com/user-attachments/assets/143b77e9-6ac7-40b4-9e28-fbefcac77471">

Also, when using the `Search` button, the `Name & code` column isn't displayed correctly at 1280px x 694px. I need to zoom out to see it properly.

**Comment by Ceibo** [comment]
It's working as expected.
In the future, we could set it to hide the columns at 1280px (including) and below.
