### ISSUE TITLE
Allow to jump to a specific page in paginated results

### ISSUE THREAD

**Issue by monsieurBelbo** [nominal-systems/dmi-api-admin-ui#56]
See @larsonel's [message](https://teams.microsoft.com/l/message/19:ZKLNUiJimB7grZJuE1nw-CP0YUg1-DlsCEaNOJk61kQ1@thread.skype/1727803157702?tenantId=a2bdfa5e-be87-4736-892b-6db8bbf91546&groupId=549d77e1-499f-494e-8922-9ad3da4e084e&parentMessageId=1727469975834&teamName=Project%20Voyager%20Development&channelName=DMI%20Broker%20Integration%20v2&createdTime=1727803157702&ngc=true&allowXTenantAccess=true).

**Comment by dwballance** [comment]
A couple of options: Have more events per page, or more pages shown (eg 20 instead of 10).
